#!/usr/bin/env bash

file="$2"
name="$1"
if [ "$#" != 2 ]
then
	echo `basename $0`: error: incorrect arguments.
	echo "Usage:  `basename $0` <function_name> <file>"
	exit 1
fi

cat << END

function r = ${name}(image, threshold)
	corners = ${name}detect(image, threshold);

	scores = zeros(size(image));

	for i=1: length(corners)
		scores(corners(i,2), corners(i, 1)) = ${name}score(image, corners(i,2), corners(i, 1));
	end


function r = ${name}score(image, x, y)
	lo = 0;
	hi = 255;




	


function r = ${name}is_corner(image, x, y, threshold)
	cb = image(y,x) + threshold;
	c_b = image(y,x) - threshold;
    
$(
	awk '
		function s(a) { return a < 0 ? a : ("+" a) }
		NR==1{next}
		NR==2{
			gsub(/[][]/, "")
			for(i=0; i < NF/2; i++)
				ac[i] = "image(y" s($(i*2+2)) ", x"s($(i*2+1))")"
			next
		}	


		{ ind = "    "substr($0, 1, match($0, /[^ ]/)-1)}
		/if_brighter/{print ind "if "ac[$2]" > cb"}
		/elsf_darker/ {print ind "elseif "ac[$2]" < c_b"}
		/if_darker/{print ind "if "ac[$2]" < c_b"}
		/if_either/{print ind "if "ac[$2]" > cb || "ac[$2]" < c_b "}
		/else/||/end/{print ind $1}
		/corner/{print ind "r = 1;"
				 print ind "return"}
		/background/{print ind "r = 0;"
				 print ind "return"}
	' $file
)

function coords = ${name}detect(image, threshold)
	sz = size(im);																
	xsize=sz(2);																
	ysize=sz(1);																
	cs = zeros(5000, 2);														
	nc = 0;																		
	for x = 4 : xsize - 3														
		for y = 4 : ysize -3						
			cb = image(y,x) + threshold;
			c_b = image(y,x) - threshold;
			
$(
			awk '
				function s(a) { return a < 0 ? a : ("+" a) }
				NR==1{next}
				NR==2{
					gsub(/[][]/, "")
					for(i=0; i < NF/2; i++)
						ac[i] = "image(y" s($(i*2+2)) ", x"s($(i*2+1))")"
					next
				}	


				{ ind = "        "substr($0, 1, match($0, /[^ ]/)-1)}
				/if_brighter/{print ind "if "ac[$2]" > cb"}
				/elsf_darker/ {print ind "elseif "ac[$2]" < c_b"}
				/if_darker/{print ind "if "ac[$2]" < c_b"}
				/if_either/{print ind "if "ac[$2]" > cb || "ac[$2]" < c_b "}
				/else/||/end/{print ind $1}
				/background/{continue}
			' $file
)
			nc = nc + 1;														
			if nc > length(cs)													
				cs(length(cs)*2,1) = 0;											
			end																	
			cs(nc,1) = x;														
			cs(nc,2) = y;			
		end
	end

	coords = cs([1:nc],:);														
END

